-- 기존에 저장되어있던 MEMBERS 테이블 삭제
DROP TABLE MEMBER;

-- 새로운 MEMBERS 테이블 생성
CREATE TABLE MEMBER (
    MID VARCHAR(10) UNIQUE NOT NULL,
    MEMAIL VARCHAR(50) CONSTRAINT U_MEMAIL UNIQUE,
    MNAME VARCHAR(10) NOT NULL
);

-- MEMBERS 테이블에 데이터 추가(삽입)
INSERT INTO MEMBER VALUES('fall', 'fall@mycompany.com' ,'홍길동');
INSERT INTO MEMBER VALUES(NULL, NULL, '홍길동');

-- MEMBERS 테이블 조회
SELECT * FROM MEMBER;

-- MEMBER 테이블의 컬럼을 조회
DESC MEMBER;


/*==========================================================*/
/*==========================================================*/


-- 기존에 저장되어있던 MEMBERS 테이블 삭제
DROP TABLE MEMBER;

-- 새로운 MEMBERS 테이블 생성
CREATE TABLE MEMBER (
    MID VARCHAR(10) NOT NULL,
    MEMAIL VARCHAR(50) NULL,
    MNAME VARCHAR(10) NOT NULL
);

-- MEMBER 테이블 제약조건 이름 직접 지정
ALTER TABLE MEMBER
    MODIFY (
        MID CONSTRAINT U_MID UNIQUE,
        MEMAIL CONSTRAINT U_MEMAIL UNIQUE
    );

-- MEMEBER 테이블 제약조건 삭제
ALTER TABLE MEMBER
    DROP CONSTRAINT U_MEMAIL;

DROP TABLE MEMBERS;

CREATE TABLE MEMBERS(
    MID VARCHAR(10) PRIMARY KEY, -- 컬럼 수정의 제약조건
    MEMAIL VARCHAR(50) NULL
);

INSERT INTO MEMBERS VALUES('winter', '한겨울'); --(O)
INSERT INTO MEMBERS VALUES('winter', '한겨울'); --(X)
INSERT INTO MEMBERS VALUES(NULL, '한겨울'); --(X)


/*==========================================================*/
/*==========================================================*/


DROP TABLE MEMBERS;

CREATE TABLE MEMBERS(
    MID VARCHAR(10) NOT NULL,
    MEMAIL VARCHAR(50) NULL
);

-- 제약조건 이름 지정하기 - 방법1 (컬럼 수정)
ALTER TABLE MEMBERS
    MODIFY ( MID CONSTRAINT PK_MID PRIMARY KEY );
-- 제약조건 이름 지정하기 - 방법2 (제약조건을 추가) 가장 많이 사용
ALTER TABLE MEMBERS
    ADD CONSTRAINT PK_MID PRIMARY KEY ( MID );

--------------------------------------

DROP TABLE MEMBERS;

CREATE TABLE MEMBERS(
    FIRST_NO CHAR(6) NOT NULL,
    SECOND_NO CHAR(7) NOT NULL,
    MEMAIL VARCHAR(50) NULL
);

/* 이 방법으로 다수의 컬럼에 기본키 지정 못함 */
ALTER TABLE MEMBERS
    MODIFY ( 
        FIRST_NO CONSTRAINT PK_SSN PRIMARY KEY,
        SECOND_NO CONSTRAINT PK_SSN PRIMARY KEY    
    );

/* 이 방법으로 다수의 컬럼에 기본키 지정 가능 (복합키) */
ALTER TABLE MEMBERS
    ADD CONSTRAINT PK_SSN PRIMARY KEY (FIRST_NO, SECOND_NO);    

--------------------------------------

DROP TABLE MEMBERS;

-- 제약조건 이름 지정하기 - 방법3 (테이블을 생성하면서 제약조건 설정)
CREATE TABLE MEMBERS(
    MID VARCHAR(10) NOT NULL,
    MEMAIL VARCHAR(50) NULL,
    CONSTRAINT PK_MID PRIMARY KEY(MID),
    CONSTRAINT U_EMAIL UNIQUE (MEMAIL)
);


/*==========================================================*/
/*==========================================================*/


DROP TABLE MEMBERS;
DROP TABLE FREEBOARDS;

CREATE TABLE MEMBERS(
    MID VARCHAR(10) NOT NULL,
    MANME VARCHAR(20) NOT NULL
);
ALTER TABLE MEMBERS
    ADD CONSTRAINT PK_MID PRIMARY KEY (MID);
    
CREATE TABLE FREEBOARDS(
    BNO NUMBER NOT NULL,
    BTITLE VARCHAR(50) NOT NULL,
    BWRITER VARCHAR(10) NOT NULL
);    
ALTER TABLE FREEBOARDS
    ADD CONSTRAINT PK_BNO PRIMARY KEY (BNO);
    
-----------------------------------

INSERT INTO MEMBERS VALUES ('fall', '김가을');
INSERT INTO FREEBOARDS VALUES (1, '단풍', 'fall');
COMMIT;
INSERT INTO FREEBOARDS VALUES (2, '눈', 'winter'); -- 이 데이터가 들어가면 안됨

-----------------------------------

DROP TABLE FREEBOARDS;
/*외래키 지정 - 방법1*/
CREATE TABLE FREEBOARDS(
    BNO NUMBER NOT NULL,
    BTITLE VARCHAR(50) NOT NULL,
    BWRITER VARCHAR(10) CONSTRAINT FK_BWRITER REFERENCES MEMBERS(MID)
); 
ALTER TABLE FREEBOARDS
    ADD CONSTRAINT PK_BNO PRIMARY KEY (BNO);
/*외래키 지정 - 방법2*/
CREATE TABLE FREEBOARDS(
    BNO NUMBER NOT NULL,
    BTITLE VARCHAR(50) NOT NULL,
    BWRITER VARCHAR(10) NOT NULL,
    CONSTRAINT FK_BWRITER FOREIGN KEY (BWRITER) REFERENCES MEMBERS(MID)
); 
ALTER TABLE FREEBOARDS
    ADD CONSTRAINT PK_BNO PRIMARY KEY (BNO);
/*외래키 지정 - 방법3 (제일 많이 씀)*/
CREATE TABLE FREEBOARDS(
    BNO NUMBER NOT NULL,
    BTITLE VARCHAR(50) NOT NULL,
    BWRITER VARCHAR(10) NOT NULL
); 
ALTER TABLE FREEBOARDS
    ADD CONSTRAINT PK_BNO PRIMARY KEY (BNO);
ALTER TABLE FREEBOARDS
    ADD CONSTRAINT FR_WRITER FOREIGN KEY (BWRITER) REFERENCES MEMBERS(MID);
INSERT INTO FREEBOARDS VALUES (1, '단풍', 'fall');
INSERT INTO FREEBOARDS VALUES (2, '눈', 'winter'); -- MEMBERS 테이블에 WINTER가 없어서 실행불가

-----------------------------------

--참조하고 있는 키는 삭제할 수 없음
DELETE FROM MEMBERS WHERE MID='fall'; --(2) 그래야 삭제 가능
DELETE FROM FREEBOARDS WHERE BNO=1; --(1) 먼저 참조되고 있는 키를 삭제
ROLLBACK;
/*방법1*/
-- 모든 참조하는 키를 포함한 행을 삭제 (위험하지만 깔끔한 방법 / 향 전체 삭제)
DROP TABLE FREEBOARDS;
CREATE TABLE FREEBOARDS(
    BNO NUMBER NOT NULL,
    BTITLE VARCHAR(50) NOT NULL,
    BWRITER VARCHAR(10) NOT NULL
); 
ALTER TABLE FREEBOARDS
    ADD CONSTRAINT PK_BNO PRIMARY KEY (BNO);
ALTER TABLE FREEBOARDS
    ADD CONSTRAINT FR_WRITER 
        FOREIGN KEY (BWRITER) REFERENCES MEMBERS(MID) ON DELETE CASCADE;
INSERT INTO MEMBERS VALUES ('fall', '김가을');
INSERT INTO FREEBOARDS VALUES (1, '단풍', 'fall');
DELETE FROM MEMBERS WHERE MID='fall'; --오류없이 잘 작동!
/*방법2*/
-- 모든 참조하는 키를 포함한 행을 삭제 (행 일부만 삭제)
DROP TABLE FREEBOARDS;
CREATE TABLE FREEBOARDS(
    BNO NUMBER NOT NULL,
    BTITLE VARCHAR(50) NOT NULL,
    BWRITER VARCHAR(10) NULL --null로 변경
); 
ALTER TABLE FREEBOARDS
    ADD CONSTRAINT PK_BNO PRIMARY KEY (BNO);
ALTER TABLE FREEBOARDS
    ADD CONSTRAINT FR_WRITER 
        FOREIGN KEY (BWRITER) 
        REFERENCES MEMBERS(MID) ON DELETE SET NULL;
INSERT INTO MEMBERS VALUES ('fall', '김가을');
INSERT INTO FREEBOARDS VALUES (1, '단풍', 'fall');
DELETE FROM MEMBERS WHERE MID='fall'; --오류없이 잘 작동!


/*==========================================================*/
/*==========================================================*/


DROP TABLE FREEBOARDS;
DROP TABLE MEMBERS;

/*방법1*/
CREATE TABLE MEMBERS(
    MID VARCHAR(20) PRIMARY KEY,
    MNAME VARCHAR(20) NOT NULL,
    MAGE NUMBER(3) CHECK(MAGE>0 AND MAGE<200),
    MGRADE CHAR(1) CHECK(MGRADE IN ('A', 'B', 'C'))
);

INSERT INTO MEMBERS
    VALUES('winter', '한겨울', 25, 'A');
INSERT INTO MEMBERS
    VALUES('winter', '한겨울', -1, 'A'); --(X)
INSERT INTO MEMBERS
    VALUES('winter', '한겨울', 400, 'A'); --(X)   
    
    
/*방법2*/
CREATE TABLE MEMBERS(
    MID VARCHAR(20) PRIMARY KEY,
    MNAME VARCHAR(20) NOT NULL,
    MAGE NUMBER(3) NOT NULL,
    MGRADE CHAR(1) NOT NULL,
    CONSTRAINT CK_MAGE CHECK(MAGE>0 AND MAGE<200),
    CONSTRAINT CK_MGRADE CHECK(MGRADE IN ('A', 'B', 'C'))
);
INSERT INTO MEMBERS
    VALUES('winter', '한겨울', 25, 'A');
INSERT INTO MEMBERS
    VALUES('winter', '한겨울', -1, 'A'); --(X)


/*방법3*/
CREATE TABLE MEMBERS(
    MID VARCHAR(20) NOT NULL,
    MNAME VARCHAR(20) NOT NULL,
    MAGE NUMBER(3) NOT NULL,
    MGRADE CHAR(1) NOT NULL
);
ALTER TABLE MEMBERS
    ADD CONSTRAINT PK_MID PRIMARY KEY (MID);
ALTER TABLE MEMBERS
    ADD CONSTRAINT CK_MAGE CHECK(MAGE>0 AND MAGE<200);
ALTER TABLE MEMBERS
    ADD CONSTRAINT CK_MGRADE CHECK(MGRADE IN ('A', 'B', 'C'));
INSERT INTO MEMBERS
    VALUES('winter', '한겨울', 25, 'A');
INSERT INTO MEMBERS
    VALUES('winter', '한겨울', -1, 'A'); --(X)    


/*==========================================================*/
/*==========================================================*/


DROP TABLE MEMBERS;
CREATE TABLE MEMBERS(
    MID VARCHAR(20) PRIMARY KEY,
    MNAME VARCHAR(20) NOT NULL,
    MDATE DATE DEFAULT SYSDATE NOT NULL, --DEFAULT
    MCITY VARCHAR(10) DEFAULT '서울' NULL,
    MGRAGE CHAR(1) DEFAULT 'C' CHECK(MGRAGE IN ('A', 'B', 'C'))
);

INSERT INTO MEMBERS
    VALUES('winter', '홍길동', DEFAULT, DEFAULT, DEFAULT);
    
INSERT INTO MEMBERS(MID, MNAME)
    VALUES('summer', '하여름');   
    
INSERT INTO MEMBERS(MID, MNAME, MCITY)
    VALUES('fall', '김단풍', NULL);    
    
SELECT * FROM MEMBERS;
